# Generated by Django 5.2.4 on 2025-08-11 07:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentID', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('sentimentID', models.AutoField(primary_key=True, serialize=False)),
                ('sentimentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceID', models.AutoField(primary_key=True, serialize=False)),
                ('serviceName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('programID', models.AutoField(primary_key=True, serialize=False)),
                ('programName', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.program')),
            ],
        ),
        migrations.CreateModel(
            name='StudentActivityLog',
            fields=[
                ('logID', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('Student logged in.', 'Student logged in.'), ('Student logged out.', 'Student logged out.')], max_length=40)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.student')),
            ],
            options={
                'verbose_name': 'Student Activity Log',
                'verbose_name_plural': 'Student Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('feedbackID', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sentiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.sentiment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.service')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('teacherName', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.program')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherEvaluation',
            fields=[
                ('evaluationid', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('submitted_by', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.program')),
                ('sentiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.sentiment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.teacher')),
            ],
        ),
    ]
