# Generated by Django 5.2.4 on 2025-08-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivitylog',
            name='activity_type',
            field=models.CharField(choices=[('Student logged in.', 'Student logged in.'), ('Student logged out.', 'Student logged out.'), ('Feedback Submit', 'Feedback Submit'), ('Profile updated.', 'Profile updated.'), ('Password changed.', 'Password changed.'), ('Student changed password.', 'Student changed password.')], max_length=40),
        ),
    ]
