# Generated by Django 5.2.4 on 2025-08-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherevaluation',
            name='submitted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
