# Generated by Django 5.2.4 on 2025-08-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherevaluation',
            name='dummy_field',
        ),
    ]
