# Generated by Django 5.2.4 on 2025-08-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_teacherevaluation_dummy_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherevaluation',
            old_name='evaluationID',
            new_name='evaluationid',
        ),
    ]
