# Generated by Django 5.2.4 on 2025-08-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_studentactivitylog_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivitylog',
            name='activity_type',
            field=models.CharField(choices=[('StudentLoggedIn', 'StudentLoggedIn'), ('StudentLoggedOut', 'StudentLoggedOut'), ('Feedback Submit', 'Feedback Submit'), ('Profile updated.', 'Profile updated.'), ('Password changed.', 'Password changed.'), ('Student changed password.', 'Student changed password.')], max_length=40),
        ),
    ]
