# Generated by Django 5.2.4 on 2025-08-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_teacherevaluation_submitted_by'),
        ('system', '0003_alter_studentactivitylog_activity_type'),
    ]

    operations = [
    ]
