# Generated by Django 5.2.4 on 2025-07-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
