# Generated by Django 5.2.4 on 2025-07-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_studentfeedback_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
