# Generated by Django 5.2.4 on 2025-09-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_merge_20250817_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivitylog',
            name='activity_type',
            field=models.CharField(choices=[('StudentLoggedIn', 'Student logged in'), ('StudentLoggedOut', 'Student logged out'), ('StudentProvidedFeedback', 'Student provided feedback'), ('Profile updated.', 'Profile updated.'), ('Password changed.', 'Password changed.'), ('Student changed password.', 'Student changed password.'), ('AccountCreated', 'Account created')], max_length=40),
        ),
    ]
