# Generated by Django 5.2.4 on 2025-07-13 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_studentfeedback_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
