# Generated by Django 5.2.4 on 2025-09-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_studentactivitylog_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivitylog',
            name='activity_type',
            field=models.CharField(choices=[('StudentLoggedIn', 'Student logged in'), ('StudentLoggedOut', 'Student logged out'), ('StudentProvidedFeedback', 'Student provided feedback'), ('Profile updated.', 'Profile updated.'), ('PasswordChanged', 'Password changed'), ('AccountCreated', 'Account created')], max_length=40),
        ),
    ]
