# Generated by Django 5.2.4 on 2025-09-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_studentactivitylog_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherevaluation',
            name='evaluationid',
            field=models.AutoField(db_column='evaluationID', primary_key=True, serialize=False),
        ),
    ]
