# Generated by Django 5.2.4 on 2025-07-13 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_studentfeedback_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='StudentActivityLog',
            fields=[
                ('logID', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('LOGIN', 'Student Login'), ('LOGOUT', 'Student Logout'), ('FEEDBACK_SUBMIT', 'Feedback Submitted'), ('FEEDBACK_VIEW', 'Feedback Viewed'), ('PROFILE_UPDATE', 'Profile Updated'), ('PASSWORD_CHANGE', 'Password Changed'), ('COURSE_VIEW', 'Course Information Viewed'), ('SERVICE_VIEW', 'Service Information Viewed'), ('DASHBOARD_ACCESS', 'Dashboard Accessed'), ('ERROR', 'Error Occurred')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.student')),
            ],
            options={
                'verbose_name': 'Student Activity Log',
                'verbose_name_plural': 'Student Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
