# Generated by Django 5.2.4 on 2025-07-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_studentfeedback_timestamp_studentactivitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentactivitylog',
            name='additional_data',
        ),
        migrations.RemoveField(
            model_name='studentactivitylog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studentactivitylog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='studentactivitylog',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='studentactivitylog',
            name='user_agent',
        ),
        migrations.AlterField(
            model_name='studentactivitylog',
            name='activity_type',
            field=models.CharField(choices=[('LOGIN', 'Student Login'), ('LOGOUT', 'Student Logout')], max_length=20),
        ),
    ]
