# Generated by Django 5.2.4 on 2025-07-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_remove_studentactivitylog_additional_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivitylog',
            name='activity_type',
            field=models.CharField(choices=[('student_logged_in', 'Student Logged In'), ('student_logged_out', 'Student Logged Out'), ('student_provided_feedback', 'Student Provided Feedback')], max_length=30),
        ),
    ]
