# Generated by Django 5.2.4 on 2025-09-11 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_studentactivitylog_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherevaluation',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.program'),
        ),
        migrations.AlterField(
            model_name='teacherevaluation',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
