# Generated by Django 5.2.4 on 2025-09-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_alter_teacherevaluation_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeedback',
            name='guest_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
