# Generated by Django 5.2.4 on 2025-07-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_alter_studentactivitylog_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivitylog',
            name='activity_type',
            field=models.CharField(choices=[('StudentLoggedIn', 'Student Logged In'), ('StudentLoggedOut', 'Student Logged Out'), ('StudentProvidedFeedback', 'Student Provided Feedback')], max_length=30),
        ),
    ]
