# Generated by Django 5.2.4 on 2025-07-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_studentactivitylog_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentactivitylog',
            name='activity_type',
            field=models.CharField(choices=[('Student logged in.', 'Student logged in.'), ('Student logged out.', 'Student logged out.')], max_length=40),
        ),
    ]
