# Generated by Django 5.2.4 on 2026-03-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_studentfeedback_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherevaluation',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacherevaluation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teacherevaluation',
            name='program',
        ),
        migrations.RemoveField(
            model_name='teacherevaluation',
            name='sentiment',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='TeacherEvaluation',
        ),
    ]
