# Generated by Django 5.2.4 on 2025-07-16 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_studentactivitylog_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='sentiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.sentiment'),
        ),
    ]
