# Generated by Django 5.2.4 on 2025-08-04 10:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_remove_student_course_program_student_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherID', models.AutoField(primary_key=True, serialize=False)),
                ('teacherName', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.program')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherEvaluation',
            fields=[
                ('evaluationID', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.program')),
                ('sentiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.sentiment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.teacher')),
            ],
        ),
    ]
