# Generated by Django 5.2.4 on 2025-08-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_teacher_teacherevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacherID',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default='T001', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
