# Generated by Django 5.2.4 on 2025-08-09 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_remove_teacher_teacherid_teacher_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherevaluation',
            name='sentiment',
        ),
        migrations.RemoveField(
            model_name='teacherevaluation',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='teacherevaluation',
            name='subject',
        ),
    ]
