# Generated by Django 5.2.4 on 2025-08-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_remove_teacher_teacherid_teacher_teacher_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherevaluation',
            old_name='subject',
            new_name='submitted_by',
        ),
        migrations.AddField(
            model_name='teacherevaluation',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
