# Generated by Django 5.2.4 on 2025-08-09 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_remove_teacherevaluation_sentiment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherevaluation',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherevaluation',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherevaluation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='system.department'),
        ),
        migrations.AlterField(
            model_name='teacherevaluation',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='system.program'),
        ),
        migrations.AlterField(
            model_name='teacherevaluation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='system.teacher'),
        ),
    ]
