"""
Django settings for UFP project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
#from dotenv import load_dotenv

# Load environment variables from .env file
#load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-du6e5_pr6n+edya3kso!$c*7z73jfl6&fql432^dhk#4^7)br=')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'
DEBUG = False
FRONTEND_URL = 'https://ufplatform.com/accounts/password_reset/'  # Used in email link
ALLOWED_HOSTS = ['127.0.0.1', 'localhost','ufplatform.com', 'www.ufplatform.com', 'ufpisu-cc.me', '157.230.243.90', 'localhost', '*']
# or
# ALLOWED_HOSTS = ['157.230.243.90', 'your-domain.com']  # production

# Make sure you have this in settings.py
LOGIN_URL = '/accounts/select/'   # The name of your login URL pattern
STUDENT_LOGIN_REDIRECT_URL = 'give_feedback'  # After successful login
STUDENT_LOGOUT_REDIRECT_URL = 'login_student'  # After logout

# Application definition
INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "import_export",
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",  # optional, if django-constance package is used
    'accounts.apps.AccountsConfig',
    'dashboard.apps.DashboardConfig',
    'system.apps.SystemConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_recaptcha',
    'rest_framework',
    'api',
    'warehouse.apps.WarehouseConfig',
    'rest_framework.authtoken',
    'django_rest_passwordreset',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'UFP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'UFP.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use dj-database-url for more flexible database configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ufp_db',
        'USER': 'ufp_user',
        'PASSWORD': 'Estevesjancen06-16-23',
        'HOST': 'localhost',   # <-- important
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'dashboard.validators.NotSameAsOldPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Manila'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# settings.py

# URL paths for browser
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = '/var/www/ufp/assets/'
MEDIA_ROOT = '/var/www/ufp/media/'

# Optional: additional static files
STATICFILES_DIRS = [
    BASE_DIR / 'staticFiles',  # if exists
]

#STATIC_ROOT = BASE_DIR / 'assets'
# Use WhiteNoise for serving static files in production
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Production security settings
#if not DEBUG:
#    SECURE_SSL_REDIRECT = True
#    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
#    SECURE_HSTS_SECONDS = 31536000
#    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#    SECURE_HSTS_PRELOAD = True
#    SECURE_CONTENT_TYPE_NOSNIFF = True
#    SECURE_BROWSER_XSS_FILTER = True
##    SESSION_COOKIE_SECURE = True
#   CSRF_COOKIE_SECURE = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

RECAPTCHA_PUBLIC_KEY = '6LeOH4YrAAAAAOoWOgDh9tE8zifaY4GlUBBuiqrO'
RECAPTCHA_PRIVATE_KEY = '6LeOH4YrAAAAABTfbLHCTRf5fRcZQdxo9VNAPg-X'

# Namecheap PrivateEmail SMTP
EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"
#EMAIL_HOST = "mail.privateemail.com"
#EMAIL_PORT = 587
SENDGRID_API_KEY = "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"
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = "no-reply@ufplatform.com"
EMAIL_HOST_PASSWORD = "Ge!O56!=Ujes"

DEFAULT_FROM_EMAIL = "University Feedback Platform <no-reply@ufplatform.com>"





REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

DJANGO_REST_PASSWORDRESET_USE_JSON = True

# Custom email template
DJANGO_REST_PASSWORDRESET_EMAIL_TEMPLATE_NAME = 'accounts/email/password_reset_email.html'


# django unfold config 
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "UFP Admin",
    "SITE_HEADER": "UFP Admin",
    "SITE_SUBHEADER": "University Feedback Platform",
    "SHOW_BACK_BUTTON": True,
    "EXTRA_CSS": [
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css",
    ],
    "EXTRA_JS": [
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/js/all.min.js",
    ],
    "SITE_SYMBOL": "speed",  # symbol from icon set
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": lambda request: static("system/images/logo1.png"),
        },
    ],
    "COLORS": {
        "primary": {
            "50": "220, 255, 220",   # very light green
            "100": "200, 255, 200",  # lighter green
            "200": "170, 255, 170",  # light green
            "300": "140, 255, 140",  # medium-light green
            "400": "100, 230, 100",  # medium greenpsy
            "500": "51, 204, 51",    # brighter main green
            "600": "0, 153, 0",      # accent green
            "700": "0, 128, 0",      # slightly darker
            "800": "0, 102, 0",      # dark green
            "900": "0, 77, 0",       # darkest green
        }
    },
    "COLORS_DARK": {
        "primary": {
            "50": "200, 255, 200",
            "100": "170, 255, 170",
            "200": "140, 255, 140",
            "300": "100, 230, 100",
            "400": "51, 204, 51",
            "500": "0, 153, 0",
            "600": "0, 128, 0",
            "700": "0, 102, 0",
            "800": "0, 77, 0",
            "900": "0, 51, 0",
        }
    },
    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        "command_search": True,  # Replace the sidebar search with the command search
        "show_all_applications": True,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": _("Authentication and Authorization"),
                "separator": True,  # Top border
                # "collapsible": True,  # Collapsible group of links (optional)
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": _("Dashboard"),
                "separator": True,
                "collapsible":True,
                "items": [
                    {
                        "title": _("OSAS Dashboard"),
                        "icon": "pie_chart",
                        "link": reverse_lazy("admin_osas_services"),
                        "permission": lambda request: request.user.is_staff,
                    },
                    {
                        "title": _("Teacher's Evaluation"),
                        "icon": "school",
                        "link": reverse_lazy("admin_teachers_evaluation"),
                        "permission": lambda request: request.user.is_staff,
                    },
                ],
            },
            {
                "title": _("System"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Services"),
                        "icon": "build",
                        "link": reverse_lazy("admin:system_service_changelist"),
                    },
                    {
                        "title": _("Departments"),
                        "icon": "apartment",
                        "link": reverse_lazy("admin:system_department_changelist"),
                    },
                    {
                        "title": _("Sentiments"),
                        "icon": "emoji_emotions",
                        "link": reverse_lazy("admin:system_sentiment_changelist"),
                    },
                    {
                        "title": _("Programs"),
                        "icon": "school",
                        "link": reverse_lazy("admin:system_program_changelist"),
                    },
                    {
                        "title": _("Students"),
                        "icon": "person",
                        "link": reverse_lazy("admin:system_student_changelist"),
                    },
                    {
                        "title": _("Feedback"),
                        "icon": "feedback",
                        "link": reverse_lazy("admin:system_studentfeedback_changelist"),
                    },
                    {
                        "title": _("Teachers"),
                        "icon": "people",
                        "link": reverse_lazy("admin:system_teacher_changelist"),
                    },
                    {
                        "title": _("Teacher Evaluation"),
                        "icon": "rate_review",
                        "link": reverse_lazy("admin:system_teacherevaluation_changelist"),
                    },
                    {
                        "title": _("Student Activity Log"),
                        "icon": "history",
                        "link": reverse_lazy("admin:system_studentactivitylog_changelist"),
                    },
                ],
            },
            {
                "title": _("Warehouse"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("FactTeacherEvaluation"),
                        "icon": "rate_review",
                        "link": reverse_lazy("admin:warehouse_fact_teacher_evaluation_changelist"),
                    },
                    {
                        "title": _("FactFeedback"),
                        "icon": "feedback",
                        "link": reverse_lazy("admin:warehouse_factfeedback_changelist"),
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "models": [
                "system.service",
                "system.department",
                "system.sentiment",
                "system.program",
                "system.student",
                "system.studentfeedback",
                "system.teacher",
                "system.teacherevaluation",
                "system.studentactivitylog",
            ],
            "items": [
                {
                    "title": _("Services"),
                    "link": reverse_lazy("admin:system_service_changelist"),
                },
                {
                    "title": _("Departments"),
                    "link": reverse_lazy("admin:system_department_changelist"),
                },
                {
                    "title": _("Sentiments"),
                    "link": reverse_lazy("admin:system_sentiment_changelist"),
                },
                {
                    "title": _("Programs"),
                    "link": reverse_lazy("admin:system_program_changelist"),
                },
                {
                    "title": _("Students"),
                    "link": reverse_lazy("admin:system_student_changelist"),
                },
                {
                    "title": _("Feedback"),
                    "link": reverse_lazy("admin:system_studentfeedback_changelist"),
                },
                {
                    "title": _("Teachers"),
                    "link": reverse_lazy("admin:system_teacher_changelist"),
                },
                {
                    "title": _("Teacher Evaluation"),
                    "link": reverse_lazy("admin:system_teacherevaluation_changelist"),
                },
                {
                    "title": _("Student Activity Log"),
                    "link": reverse_lazy("admin:system_studentactivitylog_changelist"),
                },
            ],
        },
        {
            "models": [
                "warehouse.dimservice",
                "warehouse.dimsentiment",
                "warehouse.dimstudent",
                "warehouse.dim_teacher",
                "warehouse.fact_teacher_evaluation",
                "warehouse.factfeedback",
            ],
            "items": [
                {
                    "title": _("Fact Teacher Evaluation"),
                    "link": reverse_lazy("admin:warehouse_fact_teacher_evaluation_changelist"),
                },
                {
                    "title": _("Fact Feedback"),
                    "link": reverse_lazy("admin:warehouse_factfeedback_changelist"),
                },
            ],
        },
    ],

    # Your callbacks here:
    #"ENVIRONMENT": "system.views.environment_callback",
    #"ENVIRONMENT_TITLE_PREFIX": None,
    #"DASHBOARD_CALLBACK": "system.views.dashboard_callback",
}
