# Generated by Django 5.2.4 on 2025-08-04 10:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dim_teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(blank=True, max_length=100, null=True)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('program_id', models.IntegerField(blank=True, null=True)),
                ('program_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'warehouse"."dim_teacher',
            },
        ),
        migrations.CreateModel(
            name='DimSentiment',
            fields=[
                ('sentiment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'warehouse"."dim_sentiment',
            },
        ),
        migrations.CreateModel(
            name='DimService',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'warehouse"."dim_service',
            },
        ),
        migrations.CreateModel(
            name='DimStudent',
            fields=[
                ('student_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('program_id', models.IntegerField(blank=True, null=True)),
                ('program_name', models.CharField(blank=True, max_length=100, null=True)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'warehouse"."dim_student',
            },
        ),
        migrations.CreateModel(
            name='FactFeedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('comment_length', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('sentiment', models.ForeignKey(db_column='sentiment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.dimsentiment')),
                ('service', models.ForeignKey(db_column='service_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.dimservice')),
                ('student', models.ForeignKey(db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.dimstudent')),
            ],
            options={
                'db_table': 'warehouse"."fact_feedback',
            },
        ),
    ]
